{% set name = "rosinstall_generator" %}
{% set version = "0.1.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros-infrastructure/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4c5efbb8e5be8cbb90147cbd69e469128039906e5c49193c80da3f6c6ea9a40b

build:
  noarch: python
  number: 0
  entry_points:
    - rosinstall_generator=rosinstall_generator.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - catkin_pkg >=0.1.28
    - python
    - pyyaml
    - rosdistro >=0.7.3
    - rospkg
    - setuptools

test:
  imports:
    - rosinstall_generator
  commands:
    - rosinstall_generator --help

about:
  home: http://wiki.ros.org/rosinstall_generator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A tool for generating rosinstall files

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
